Tokenizer almost finished
hv14/CodeU-Summer-2017 pull request #3
Opened 2017-06-03 16:44 UTC by FearsomeMango73

I discovered this did not go through to Himani's Repo... trying again

This is the partially completed Tokenizer Input portion of the first set of outlines. There are two sections of suedo code that still need to be replaced in the next() of the Tokienzer.java class and the constructor of the same file I am having a little trouble with. Everything else should be there :) and I am working to figure out these issues as we speak :)
Learning more about Github everyday :P
*I was think maybe Kevin and I can talk things through on this? or if anyone wants to stay after the meeting to talk through code?*

2017-06-03 18:28 UTC, chriscraws requested changes
We'll talk about best practices for Git in the meeting - this pull request currently adds 5 new files to the root directory - but these files mostly already exist in the project. Instead of creating new ones, the existing ones should be modified. That way the pull request is specific to the per-line changes you've made.

After the meeting, you should keep this code on the side and re-follow the tutorial after setting up from git closely following the guides - and as a general rule if something seems like it's going to take more than 15-30 minutes to figure out then don't hesitate to ask the group or ask me!

2017-06-15 22:14 UTC, chriscraws requested changes
Woo! Things look pretty good. Here's some next steps:

5 of the files are in the wrong place and/or are duplicates. These are Chat.java, Panel.java, TestRunner.java, Tokenizer.java, and TokenizerTest.java. All of them are in the base-directory of your repository. 

Tokenizer and TokenizerTest are duplicate files that can be removed:

Make sure you're in the root-directory of the repository and run `git rm TokenizerTest.java Tokenizer.java`

Chat, Panel, and TestRunner already exist in the codebase and your changes should be made to those files instead. Using copy/paste to place them in their proper locations, overwriting the old values should work. 

*After* that is done, you can run 

`git rm Chat.java Panel.java TestRunner.java`

You can commit these changes with something like `git commit -m "Moved files back into src directory"`

Once all that is done, I have a few comments on the remaining files for changes to make before you push.

Let me know if you run into any trouble or have clarifying questions!

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +  // Skip all leading whitespace
This comment should go below the initialization of `tokenCreation`

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +    String tokenCreation = "";
You can keep this initialization simple as `String tokenCreation;` since we never make use of any value before assigning it to something new

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +      tokenCreation += readWithNoQuotes(); //need to check
1. You should use `=` assignment instead of `+=` concatenation here
2. If `peek()` is returning that the next character is a `"`, then you should use your function that tokenizes input that begins with `"`. Use `readWithQuotes()` here instead :)

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +      tokenCreation += readWithQuotes(); //need to check
You'll need to change this line too :)

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/TokenizerTest.java
> +   assertEquals(tokenizer.next(), �how are you�);
Add one space here so the indentation matches up

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/TokenizerTest.java
> +}
Add one more newline at the end, just to keep this file consistent with the others

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +    }
These two lines need their indentation fixed, also there should be an empty line after this function definition

2017-06-15 22:14 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +  }
One more newline here too, just for consistency!

2017-06-25 21:12 UTC, chriscraws requested changes
Is this all wrapped up? If so, just a couple small changes and then let me know so I can run it and give LGTM :)

2017-06-25 21:12 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +//there are two parts in the next() funtion that I still need to complete
The next function is all done now right? you can remove this comment

2017-06-25 21:12 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> + // Skip all leading whitespace
add an indent here

2017-06-26 22:13 UTC, chriscraws requested changes
All of the quotation marks are the `“` character instead of the `"` character, which is causing build-issues for me. When I replace them, I still have a list of build errors with various symbols not being found - does this build on your computer?

2017-08-04 23:37 UTC, chriscraws requested changes
Looks great! Just two changes then go ahead and merge it in :)

2017-08-04 23:37 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +  private int at;
I'd rename this variable to something a little more clear, like characterPosition

2017-08-04 23:37 UTC, chriscraws commented on src/codeu/chat/util/Tokenizer.java
> +        tokenCreation = readWithQuotes(); //need to check
Not sure what the 'need to check' comment means - can it be removed?

2017-08-05 00:02 UTC, FearsomeMango73 commented on src/codeu/chat/util/Tokenizer.java
> +        tokenCreation = readWithQuotes(); //need to check
It has been removed, that was for my personal thought earlier on

2017-08-05 00:11 UTC, merged